@baseUrl = localhost:3003

###

# @name createTrip
POST http://{{baseUrl}}/trips
Content-Type: application/json

{
  "destination": "Curitiba",
  "starts_at": "2024-10-01 18:00:00",
  "ends_at": "2024-10-15 18:00:00",
  "owner_name": "Igor Barbosa",
  "owner_email": "igor@acme.com",
  "emails_to_invite": [
    "igor@gmail.com",
    "johndoe@gmail.com"
  ]
}

###

# @name updateTrip
PUT http://{{baseUrl}}/trips/9650ccbd-3f92-48b0-85fa-488bd0a97fb7
Content-Type: application/json

{
  "destination": "Curitiba - PR",
  "starts_at": "2024-10-01 18:00:00",
  "ends_at": "2024-10-15 18:00:00"
}

###

# @name getTripDetails
GET http://{{baseUrl}}/trips/9650ccbd-3f92-48b0-85fa-488bd0a97fb7

###

# @name confirmTrip
GET http://{{baseUrl}}/trips/9650ccbd-3f92-48b0-85fa-488bd0a97fb7/confirm

###

# @name confirmParticipant
GET http://{{baseUrl}}/participants/4d82111d-c0bd-4e33-bb03-f84b02234303/confirm

###

# @name getParticipant
GET http://{{baseUrl}}/participants/4d82111d-c0bd-4e33-bb03-f84b02234303

###

# @name createActivity
POST http://{{baseUrl}}/trips/9650ccbd-3f92-48b0-85fa-488bd0a97fb7/activities
Content-Type: application/json

{
  "title": "Almoço",
  "occurs_at": "2024-10-14 12:00:00"
}

###

# @name getActivities
GET http://{{baseUrl}}/trips/9650ccbd-3f92-48b0-85fa-488bd0a97fb7/activities

###
# @name createLink
POST http://{{baseUrl}}/trips/9650ccbd-3f92-48b0-85fa-488bd0a97fb7/links
Content-Type: application/json

{
  "title": "Reserva do AirBnB",
  "url": "https://airbnb.com/reserva-journey"
}

###

# @name getLinks
GET http://{{baseUrl}}/trips/9650ccbd-3f92-48b0-85fa-488bd0a97fb7/links

###

# @name getParticipants
GET http://{{baseUrl}}/trips/9650ccbd-3f92-48b0-85fa-488bd0a97fb7/participants

###
# @name createInvite
POST http://{{baseUrl}}/trips/9650ccbd-3f92-48b0-85fa-488bd0a97fb7/invites
Content-Type: application/json

{
  "email": "teste@mail.com"
}

