@baseUrl = localhost:3003

GET http://{{baseUrl}}/listar

###
# @name createTrip
POST http://{{baseUrl}}/trips
Content-Type: application/json

{
  "destination": "Curitiba",
  "starts_at": "2024-10-01 18:00:00",
  "ends_at": "2024-10-15 18:00:00",
  "owner_name": "Igor Barbosa",
  "owner_email": "igor@acme.com",
  "emails_to_invite": [
    "igor@gmail.com",
    "johndoe@gmail.com"
  ]
}